package item

var AllItems = []Item{
	// Test Items

	&Weapon{damage: 15, weight: 40, name: "Common Sword", rarity: Common},
	&Weapon{damage: 25, weight: 45, name: "Rare Sword", rarity: Rare},
	&Weapon{damage: 40, weight: 50, name: "Epic Sword", rarity: Epic},
	&Weapon{damage: 60, weight: 55, name: "Legendary Sword", rarity: Legendary},

	&Weapon{damage: 10, weight: 30, name: "Common Bow", rarity: Common},
	&Weapon{damage: 20, weight: 35, name: "Rare Bow", rarity: Rare},
	&Weapon{damage: 35, weight: 38, name: "Epic Bow", rarity: Epic},
	&Weapon{damage: 50, weight: 40, name: "Legendary Bow", rarity: Legendary},

	// Common weapons
	&Weapon{name: "Rusty Sword", damage: 10, rarity: Common, weight: 30},
	&Weapon{name: "Wooden Club", damage: 8, rarity: Common, weight: 25},
	&Weapon{name: "Iron Dagger", damage: 12, rarity: Common, weight: 15},
	&Weapon{name: "Stone Axe", damage: 14, rarity: Common, weight: 35},
	&Weapon{name: "Bronze Short Sword", damage: 15, rarity: Common, weight: 28},
	&Weapon{name: "Hunting Knife", damage: 11, rarity: Common, weight: 12},
	&Weapon{name: "Farmer’s Pitchfork", damage: 13, rarity: Common, weight: 30},
	&Weapon{name: "Copper Mace", damage: 16, rarity: Common, weight: 32},
	&Weapon{name: "Reinforced Stick", damage: 9, rarity: Common, weight: 18},
	&Weapon{name: "Training Sword", damage: 10, rarity: Common, weight: 20},
	&Weapon{name: "Broken Blade", damage: 7, rarity: Common, weight: 10},
	&Weapon{name: "Hunting Spear", damage: 14, rarity: Common, weight: 25},
	&Weapon{name: "Wooden Bow", damage: 12, rarity: Common, weight: 18},
	&Weapon{name: "Stone Hammer", damage: 17, rarity: Common, weight: 40},
	&Weapon{name: "Iron Hatchet", damage: 13, rarity: Common, weight: 28},
	&Weapon{name: "Rusty Halberd", damage: 18, rarity: Common, weight: 45},
	&Weapon{name: "Cracked Flail", damage: 11, rarity: Common, weight: 33},
	&Weapon{name: "Carved Shortbow", damage: 15, rarity: Common, weight: 20},
	&Weapon{name: "Simple Staff", damage: 8, rarity: Common, weight: 22},
	&Weapon{name: "Traveler’s Knife", damage: 10, rarity: Common, weight: 12},
	&Weapon{name: "Trainee’s Pike", damage: 16, rarity: Common, weight: 38},
	&Weapon{name: "Farmer’s Hoe", damage: 9, rarity: Common, weight: 25},
	&Weapon{name: "Stone Blade", damage: 13, rarity: Common, weight: 26},
	&Weapon{name: "Basic Crossbow", damage: 14, rarity: Common, weight: 30},
	&Weapon{name: "Iron Baton", damage: 10, rarity: Common, weight: 18},
	&Weapon{name: "Worn Saber", damage: 17, rarity: Common, weight: 28},
	&Weapon{name: "Bronze Cleaver", damage: 18, rarity: Common, weight: 32},
	&Weapon{name: "Wooden Staff", damage: 9, rarity: Common, weight: 22},
	&Weapon{name: "Simple Sling", damage: 11, rarity: Common, weight: 10},
	&Weapon{name: "Iron Shard Blade", damage: 16, rarity: Common, weight: 30},
	&Weapon{name: "Training Spear", damage: 13, rarity: Common, weight: 24},
	&Weapon{name: "Worn Dirk", damage: 12, rarity: Common, weight: 15},
	&Weapon{name: "Copper Warhammer", damage: 19, rarity: Common, weight: 42},
	&Weapon{name: "Battered Lance", damage: 20, rarity: Common, weight: 48},
	&Weapon{name: "Basic Recurve Bow", damage: 14, rarity: Common, weight: 22},
	&Weapon{name: "Iron Shortsword", damage: 16, rarity: Common, weight: 28},
	&Weapon{name: "Farmer’s Cleaver", damage: 15, rarity: Common, weight: 35},

	// Rare weapons
	&Weapon{name: "Steel Sword", damage: 25, rarity: Rare, weight: 35},
	&Weapon{name: "Battle Axe", damage: 30, rarity: Rare, weight: 45},
	&Weapon{name: "Knight’s Halberd", damage: 32, rarity: Rare, weight: 50},
	&Weapon{name: "Elven Longbow", damage: 28, rarity: Rare, weight: 25},
	&Weapon{name: "Silver Dagger", damage: 23, rarity: Rare, weight: 18},
	&Weapon{name: "Reinforced Mace", damage: 26, rarity: Rare, weight: 40},
	&Weapon{name: "Tempered Pike", damage: 29, rarity: Rare, weight: 38},
	&Weapon{name: "Forged Shortsword", damage: 24, rarity: Rare, weight: 32},
	&Weapon{name: "Heavy Warhammer", damage: 33, rarity: Rare, weight: 55},
	&Weapon{name: "Falcon Bow", damage: 27, rarity: Rare, weight: 22},
	&Weapon{name: "Soldier’s Blade", damage: 26, rarity: Rare, weight: 34},
	&Weapon{name: "Twin Iron Daggers", damage: 25, rarity: Rare, weight: 20},
	&Weapon{name: "Crossbow of Discipline", damage: 30, rarity: Rare, weight: 38},
	&Weapon{name: "Ashen Axe", damage: 31, rarity: Rare, weight: 46},
	&Weapon{name: "Steel Katana", damage: 28, rarity: Rare, weight: 30},
	&Weapon{name: "Bronze Pike", damage: 27, rarity: Rare, weight: 36},
	&Weapon{name: "Mercenary Saber", damage: 29, rarity: Rare, weight: 33},
	&Weapon{name: "Hunter’s Recurve Bow", damage: 25, rarity: Rare, weight: 24},
	&Weapon{name: "Tempered Blade", damage: 31, rarity: Rare, weight: 35},
	&Weapon{name: "Warrior’s Club", damage: 32, rarity: Rare, weight: 44},
	&Weapon{name: "Iron Lance", damage: 33, rarity: Rare, weight: 40},
	&Weapon{name: "Polished Broadsword", damage: 30, rarity: Rare, weight: 37},
	&Weapon{name: "Blessed Flail", damage: 28, rarity: Rare, weight: 39},
	&Weapon{name: "Heavy Composite Bow", damage: 27, rarity: Rare, weight: 28},
	&Weapon{name: "Steel Cleaver", damage: 32, rarity: Rare, weight: 43},
	&Weapon{name: "Rune Etched Saber", damage: 30, rarity: Rare, weight: 35},
	&Weapon{name: "Knight’s Crossbow", damage: 31, rarity: Rare, weight: 36},
	&Weapon{name: "Ornate Warhammer", damage: 33, rarity: Rare, weight: 48},
	&Weapon{name: "Battlefield Pike", damage: 30, rarity: Rare, weight: 42},
	&Weapon{name: "Ironwood Longbow", damage: 26, rarity: Rare, weight: 24},
	&Weapon{name: "Tempered Katana", damage: 29, rarity: Rare, weight: 33},
	&Weapon{name: "Steel Greatsword", damage: 34, rarity: Rare, weight: 48},
	&Weapon{name: "Dragonbone Knife", damage: 27, rarity: Rare, weight: 20},
	&Weapon{name: "Black Iron Axe", damage: 32, rarity: Rare, weight: 46},
	&Weapon{name: "Royal Pike", damage: 30, rarity: Rare, weight: 40},
	&Weapon{name: "Forged Reaver", damage: 33, rarity: Rare, weight: 44},
	&Weapon{name: "Gladiator’s Mace", damage: 31, rarity: Rare, weight: 42},

	// Epic weapons
	&Weapon{name: "Runeblade", damage: 42, rarity: Epic, weight: 35},
	&Weapon{name: "Dragonbone Axe", damage: 45, rarity: Epic, weight: 50},
	&Weapon{name: "Obsidian Bow", damage: 40, rarity: Epic, weight: 30},
	&Weapon{name: "Bloodforged Sword", damage: 43, rarity: Epic, weight: 40},
	&Weapon{name: "Vortex Halberd", damage: 47, rarity: Epic, weight: 52},
	&Weapon{name: "Crimson Edge", damage: 44, rarity: Epic, weight: 38},
	&Weapon{name: "Spectral Dagger", damage: 41, rarity: Epic, weight: 22},
	&Weapon{name: "Sunsteel Spear", damage: 46, rarity: Epic, weight: 48},
	&Weapon{name: "Frostbite Longbow", damage: 43, rarity: Epic, weight: 26},
	&Weapon{name: "Twilight Katana", damage: 42, rarity: Epic, weight: 32},
	&Weapon{name: "Stormbreaker Hammer", damage: 48, rarity: Epic, weight: 55},
	&Weapon{name: "Shadow Pike", damage: 44, rarity: Epic, weight: 42},
	&Weapon{name: "Blazeborn Saber", damage: 45, rarity: Epic, weight: 40},
	&Weapon{name: "Soulrend Mace", damage: 47, rarity: Epic, weight: 50},
	&Weapon{name: "Eternal Recurve", damage: 43, rarity: Epic, weight: 28},
	&Weapon{name: "Infernal Cleaver", damage: 46, rarity: Epic, weight: 49},
	&Weapon{name: "Dreadfang Sword", damage: 44, rarity: Epic, weight: 41},

	// Legendary weapons
	&Weapon{name: "The Worldbreaker", damage: 60, rarity: Legendary, weight: 55},
	&Weapon{name: "Eclipse Fang", damage: 65, rarity: Legendary, weight: 52},
	&Weapon{name: "Soulfire Edge", damage: 63, rarity: Legendary, weight: 45},
	&Weapon{name: "Crownsplitter", damage: 68, rarity: Legendary, weight: 58},
	&Weapon{name: "Oblivion’s Wrath", damage: 70, rarity: Legendary, weight: 60},
	&Weapon{name: "Vow of the Forgotten", damage: 72, rarity: Legendary, weight: 50},
	&Weapon{name: "Heaven’s Ruin", damage: 75, rarity: Legendary, weight: 56},

	////////////////WEARABLES////////////

	// Common wearables

	&Wearable{defense: 13, weight: 10, name: "Three Stripes", slot: WEAR_POSITION_LOWER_BODY, rarity: Common},

	&Wearable{name: "Leather Cap", defense: 10, rarity: Common, weight: 15, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Padded Vest", defense: 18, rarity: Common, weight: 25, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Cloth Trousers", defense: 12, rarity: Common, weight: 20, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Worn Boots", defense: 8, rarity: Common, weight: 10, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Traveler’s Hood", defense: 9, rarity: Common, weight: 12, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Linen Shirt", defense: 10, rarity: Common, weight: 15, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Leather Breeches", defense: 13, rarity: Common, weight: 22, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Rugged Sandals", defense: 7, rarity: Common, weight: 8, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Bronze Helm", defense: 15, rarity: Common, weight: 30, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Chain Shirt", defense: 20, rarity: Common, weight: 35, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Leather Pants", defense: 14, rarity: Common, weight: 25, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Iron-Toed Boots", defense: 11, rarity: Common, weight: 18, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Farmer’s Hat", defense: 6, rarity: Common, weight: 6, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Woven Shirt", defense: 9, rarity: Common, weight: 14, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Stitched Leggings", defense: 10, rarity: Common, weight: 18, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Leather Slippers", defense: 8, rarity: Common, weight: 10, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Iron Helmet", defense: 18, rarity: Common, weight: 30, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Padded Armor", defense: 22, rarity: Common, weight: 32, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Traveler’s Pants", defense: 15, rarity: Common, weight: 23, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Tough Boots", defense: 13, rarity: Common, weight: 15, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Hooded Cloak", defense: 11, rarity: Common, weight: 16, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Linen Robe", defense: 14, rarity: Common, weight: 22, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Basic Greaves", defense: 16, rarity: Common, weight: 25, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Simple Shoes", defense: 9, rarity: Common, weight: 9, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Bronze Cap", defense: 13, rarity: Common, weight: 20, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Leather Vest", defense: 17, rarity: Common, weight: 26, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Wool Pants", defense: 10, rarity: Common, weight: 14, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Dusty Boots", defense: 12, rarity: Common, weight: 12, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Iron Mask", defense: 19, rarity: Common, weight: 32, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Chain Tunic", defense: 21, rarity: Common, weight: 36, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Leather Trousers", defense: 15, rarity: Common, weight: 20, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Traveler’s Boots", defense: 11, rarity: Common, weight: 13, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Cloth Cap", defense: 7, rarity: Common, weight: 8, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Iron Chestplate", defense: 25, rarity: Common, weight: 40, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Bronze Greaves", defense: 18, rarity: Common, weight: 28, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Iron Boots", defense: 15, rarity: Common, weight: 20, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Tattered Hood", defense: 9, rarity: Common, weight: 10, slot: WEAR_POSITION_HEAD},

	// Rare wearables
	&Wearable{name: "Steel Helm", defense: 25, rarity: Rare, weight: 35, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Knight’s Armor", defense: 35, rarity: Rare, weight: 50, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Chain Leggings", defense: 28, rarity: Rare, weight: 38, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Steel Boots", defense: 22, rarity: Rare, weight: 28, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Silver Circlet", defense: 20, rarity: Rare, weight: 15, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Reinforced Jerkin", defense: 27, rarity: Rare, weight: 32, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Ironplate Leggings", defense: 30, rarity: Rare, weight: 42, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Tempered Greaves", defense: 29, rarity: Rare, weight: 40, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Blessed Sandals", defense: 21, rarity: Rare, weight: 20, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Hunter’s Cap", defense: 23, rarity: Rare, weight: 18, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Royal Tunic", defense: 26, rarity: Rare, weight: 30, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Scaled Pants", defense: 28, rarity: Rare, weight: 33, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Knight’s Sabatons", defense: 25, rarity: Rare, weight: 30, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Dragonbone Helm", defense: 32, rarity: Rare, weight: 45, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Iron Plate", defense: 34, rarity: Rare, weight: 50, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Tempered Greaves", defense: 30, rarity: Rare, weight: 42, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Ironshod Boots", defense: 27, rarity: Rare, weight: 33, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Silver Mask", defense: 24, rarity: Rare, weight: 22, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Hardened Jerkin", defense: 28, rarity: Rare, weight: 35, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Soldier’s Greaves", defense: 29, rarity: Rare, weight: 36, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Vanguard Boots", defense: 26, rarity: Rare, weight: 30, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Templar Helm", defense: 31, rarity: Rare, weight: 40, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Chain Armor", defense: 32, rarity: Rare, weight: 48, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Warden Legplates", defense: 33, rarity: Rare, weight: 42, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Steel Shoes", defense: 28, rarity: Rare, weight: 25, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Reinforced Helmet", defense: 29, rarity: Rare, weight: 38, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Battleplate", defense: 36, rarity: Rare, weight: 52, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Knight’s Tassets", defense: 32, rarity: Rare, weight: 40, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Heavy Greaves", defense: 27, rarity: Rare, weight: 34, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Sentinel Hood", defense: 25, rarity: Rare, weight: 20, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Steel Brigandine", defense: 33, rarity: Rare, weight: 48, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Iron Chain Pants", defense: 31, rarity: Rare, weight: 38, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Royal Boots", defense: 29, rarity: Rare, weight: 26, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Forged Helm", defense: 30, rarity: Rare, weight: 35, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Warlord Armor", defense: 37, rarity: Rare, weight: 55, slot: WEAR_POSITION_UPPER_BODY},

	// Epic wearables
	&Wearable{name: "Helm of Embersteel", defense: 42, rarity: Epic, weight: 40, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Dragonscale Plate", defense: 50, rarity: Epic, weight: 60, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Leggings of Twilight", defense: 46, rarity: Epic, weight: 48, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Boots of the Warden", defense: 40, rarity: Epic, weight: 38, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Crown of Thorns", defense: 43, rarity: Epic, weight: 35, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Vest of the Fallen", defense: 48, rarity: Epic, weight: 52, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Pants of Ruin", defense: 45, rarity: Epic, weight: 46, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Greaves of Valor", defense: 41, rarity: Epic, weight: 40, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Helm of Whispers", defense: 44, rarity: Epic, weight: 37, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Breastplate of Fury", defense: 51, rarity: Epic, weight: 58, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Shadow Legguards", defense: 47, rarity: Epic, weight: 45, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Boots of Endurance", defense: 43, rarity: Epic, weight: 36, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Crown of Radiance", defense: 46, rarity: Epic, weight: 38, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Warlord’s Cuirass", defense: 53, rarity: Epic, weight: 62, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Runeforged Legplates", defense: 49, rarity: Epic, weight: 50, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Ironstride Boots", defense: 44, rarity: Epic, weight: 39, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Helm of the Phoenix", defense: 45, rarity: Epic, weight: 42, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Chestguard of Storms", defense: 52, rarity: Epic, weight: 60, slot: WEAR_POSITION_UPPER_BODY},

	// Legendary wearables
	&Wearable{name: "Crown of Eternity", defense: 65, rarity: Legendary, weight: 45, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Armor of the Abyss", defense: 75, rarity: Legendary, weight: 70, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Legplates of Desolation", defense: 68, rarity: Legendary, weight: 60, slot: WEAR_POSITION_LOWER_BODY},
	&Wearable{name: "Greaves of the Celestial", defense: 63, rarity: Legendary, weight: 50, slot: WEAR_POSITION_FOOT},
	&Wearable{name: "Helm of the Void", defense: 66, rarity: Legendary, weight: 48, slot: WEAR_POSITION_HEAD},
	&Wearable{name: "Chestplate of Infinity", defense: 77, rarity: Legendary, weight: 72, slot: WEAR_POSITION_UPPER_BODY},
	&Wearable{name: "Leggings of the Fallen Star", defense: 70, rarity: Legendary, weight: 58, slot: WEAR_POSITION_LOWER_BODY},
}
