package battle

import (
	"github.com/Durelius/INTEproj/internal/enemy"
	"github.com/Durelius/INTEproj/internal/player"
)


type Battle struct {
	Player *player.Player
	Enemy  enemy.Enemy
	playerTurn   bool // true if it's player's turn, false if enemy's turn
	status Status
}

type Status int
const (
	Victory Status = iota
	Defeat
	Ongoing
)

// Turn should be randomly generated by the gamestate when creating a new battle.
func New(p *player.Player, e enemy.Enemy, turn bool) *Battle {
	return &Battle{
		Player: p,	
		Enemy:  e,
		playerTurn:   turn,
		status : Ongoing,
	}
}

func (b *Battle) PlayerTurn() bool {
	return b.playerTurn
}


// ProgressFight advances the fight by one turn. Either the player or the enemy attacks, depending on whose turn it is.
func(b *Battle) ProgressFight() {
	if b.status != Ongoing {	// If battle is over, do nothing
		return
	}

	if b.playerTurn {
		// Player's turn
		damage := b.Player.GetDamage()
		b.Enemy.TakeDamage(damage)
		b.playerTurn = false
	} else {
		// Enemy's turn
		damage := b.Enemy.GetDamage()
		b.Player.ReceiveDamage(damage)
		b.playerTurn = true
	}


	if b.Enemy.GetCurrentHealth() == 0 {
		b.status = Victory
		b.Player.IncreaseExperience(b.Enemy.GetXPDrop())
	}
	if b.Player.GetCurrentHealth() == 0 {
		b.status = Defeat
	}
}


func (b *Battle) GetStatus() Status {
	return b.status
}

func (b *Battle) IsOver() bool {
	return b.status != Ongoing
}